apiVersion: apps/v1
kind: Deployment
metadata:
  name: geoip
  labels:
    app: geoip
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: geoip
  template:
    metadata:
      labels:
        app: geoip
    spec:
      containers:
        - name: geoip
          image: alvonellos/geoip:$BUILD_NUMBER #The Docker image
          imagePullPolicy: Always
          ports:
            - containerPort: 8003
              hostPort: 8003
              hostIP: 0.0.0.0
              protocol: "TCP"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault
                  key: TOKEN