apiVersion: apps/v1
kind: Deployment
metadata:
  name: jizzed-www #The name of the Kubernetes Deployment to be created in the Kubernetes cluster
  labels:
    app: jizzed-www
spec:
  replicas: 2 #The number of pods to be created in the Kubernetes cluster for the React.js application container
  selector:
    matchLabels:
      app: jizzed-www
  template:
    metadata:
      labels:
        app: jizzed-www
    spec:
      containers:
        - name: jizzed-www #The name of the container
          image: alvonellos/jizzed-www:$BUILD_NUMBER #The Docker image
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              hostPort: 8080
              hostIP: 0.0.0.0
              protocol: "TCP"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault
                  key: TOKEN


   #The port for the spring application   container