apiVersion: v1
kind: Service
metadata:
  name: geoip-lb #The name of the Kubernetes Service to be created in the Kubernetes cluster
spec:
  selector:
    app: geoip
  type: LoadBalancer #Type of the Kubernetes Service
  externalIPs:
    - 172.16.253.3
  loadBalancerIP: 172.16.253.3
  ports:
    - port: 80 #Service port
      targetPort: 8003
      protocol: TCP
      #The port for the container