apiVersion: v1
kind: Service
metadata:
  name: geoip-lb #The name of the Kubernetes Service to be created in the Kubernetes cluster
spec:
  selector:
    app: geoip
  type: LoadBalancer #Type of the Kubernetes Service
  externalIPs:
    - 192.168.0.74
  loadBalancerIP: 192.168.0.74
  ports:
    - port: 80 #Service port
      targetPort: 8080
      protocol: TCP
      #The port for the container